# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_model', '0003_auto_20171016_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnistimage',
            name='image',
            field=models.ImageField(default='MNIST_images/one_1.png', upload_to='MNIST_images'),
        ),
        migrations.AlterField(
            model_name='mnistimage',
            name='predicted_label',
            field=models.IntegerField(choices=[(1, 'even'), (2, 'odd')], null=True),
        ),
        migrations.AlterField(
            model_name='mnistimage',
            name='trained_label',
            field=models.IntegerField(choices=[(1, 'even'), (2, 'odd')], null=True),
        ),
    ]
