# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_model', '0005_auto_20171020_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnistimage',
            name='predicted_label',
            field=models.IntegerField(choices=[(1, 'even'), (2, 'odd'), (3, 'Null')], default=3),
        ),
        migrations.AlterField(
            model_name='mnistimage',
            name='trained_label',
            field=models.IntegerField(choices=[(1, 'even'), (2, 'odd'), (3, 'Null')], default=3),
        ),
    ]
